dist: xenial
language: go

env:
  global:
    - GO111MODULE=on

go:
  - "1.16.x"
  - "1.15.x"

git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Anything in before_script that returns a nonzero exit code will flunk the
# build and immediately stop. It's sorta like having set -e enabled in bash.
# Make sure golangci-lint is vendored.
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -race -coverpkg ./... -coverprofile coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
